---
openapi: "3.0.0"
info:
  title: "Generated API"
  version: "1.0.0"
  description: "API dynamically generated from UML."
servers:
- url: "http://localhost:4010"
paths:
  /plant:
    get:
      tags:
      - "Plant"
      summary: "Get all instances of Plant"
      description: "Fetches all instances of Plant"
      responses:
        "200":
          description: "Successful retrieval"
          content:
            application/xml:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Plant"
                xml:
                  wrapped: true
                  name: "plant"
                  namespace: "http://example.com/schema"
              examples:
                exampleArray:
                  value:
                  - id: 1
                    plantType: "\"Evergreen Shrub\""
                  - id: 2
                    plantType: "For the Plant with id 2, the unique example value\
                      \ for the plantType attribute could be \"Cactus\"."
                  - id: 3
                    plantType: "For Plant with id 3, the unique example value for\
                      \ the plantType attribute could be \"Succulent\"."
                  - id: 4
                    plantType: "\"Orchid\""
                  - id: 5
                    plantType: "For plant with id 5, the unique example value for\
                      \ the plantType attribute could be \"Bromeliad\"."
                  - id: 6
                    plantType: "For Plant with id 6, the unique example value for\
                      \ the plantType attribute could be \"Climbing Rose\"."
                  - id: 7
                    plantType: "Ferns and Mosses"
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Plant"
                type: "array"
              examples:
                exampleArray:
                  value:
                  - id: 1
                    plantType: "\"Evergreen Shrub\""
                  - id: 2
                    plantType: "For the Plant with id 2, the unique example value\
                      \ for the plantType attribute could be \"Cactus\"."
                  - id: 3
                    plantType: "For Plant with id 3, the unique example value for\
                      \ the plantType attribute could be \"Succulent\"."
                  - id: 4
                    plantType: "\"Orchid\""
                  - id: 5
                    plantType: "For plant with id 5, the unique example value for\
                      \ the plantType attribute could be \"Bromeliad\"."
                  - id: 6
                    plantType: "For Plant with id 6, the unique example value for\
                      \ the plantType attribute could be \"Climbing Rose\"."
                  - id: 7
                    plantType: "Ferns and Mosses"
  /book:
    get:
      tags:
      - "Book"
      summary: "Get all instances of Book"
      description: "Fetches all instances of Book"
      responses:
        "200":
          description: "Successful retrieval"
          content:
            application/xml:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Book"
                xml:
                  wrapped: true
                  name: "book"
                  namespace: "http://example.com/schema"
              examples:
                exampleArray:
                  value:
                  - id: 1
                    title: "\"The Enchanted Forest\""
                    isbn: "For Book with id 1, a unique example value for the isbn\
                      \ attribute could be \"978-1-250-75241-0\"."
                    publicationYear: "A unique example value for publicationYear for\
                      \ a Book with id 1 could be 2003."
                  - id: 2
                    title: "The unique example value for the String attribute title\
                      \ of a Book with id 2 could be \"The Enigma of Probability\"\
                      ."
                    isbn: "For Book with id 2, a unique example value for the isbn\
                      \ attribute could be \"978-1-250-23-4567\"."
                    publicationYear: "The unique example value for the publicationYear\
                      \ attribute for Book with id 2 is 2018."
                  - id: 3
                    title: "\"The Great Gatsby\""
                    isbn: "The unique example value for the isbn attribute of a Book\
                      \ with id 3 could be \"978-1-56619-909-4\"."
                    publicationYear: "The unique publicationYear value for Book with\
                      \ id 3 is 2007."
                  - id: 4
                    title: "\"The Art of War\""
                    isbn: "For Book with id 4, a unique ISBN value could be \"978-1-4082-9997-3\"\
                      ."
                    publicationYear: "For Book with id 4, the publicationYear could\
                      \ be 2005."
                  - id: 5
                    title: "\"The Adventure of the Mysterious Island\""
                    isbn: "B6789451234"
                    publicationYear: "For Book with id 5, the publicationYear could\
                      \ be 2007."
                  - id: 6
                    title: "\"The Secret Life of Bees\""
                    isbn: "\"978-1-56619-909-4\""
                    publicationYear: "For Book with id 6, the unique publicationYear\
                      \ attribute value could be 2004."
                  - id: 7
                    title: "The unique title for Book with id 7 is \"The Midnight\
                      \ Library\"."
                    isbn: "\"978-0-306-40615-7\""
                    publicationYear: "For the Book with id 7, the unique publicationYear\
                      \ value could be 2005."
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Book"
                type: "array"
              examples:
                exampleArray:
                  value:
                  - id: 1
                    title: "\"The Enchanted Forest\""
                    isbn: "For Book with id 1, a unique example value for the isbn\
                      \ attribute could be \"978-1-250-75241-0\"."
                    publicationYear: "A unique example value for publicationYear for\
                      \ a Book with id 1 could be 2003."
                  - id: 2
                    title: "The unique example value for the String attribute title\
                      \ of a Book with id 2 could be \"The Enigma of Probability\"\
                      ."
                    isbn: "For Book with id 2, a unique example value for the isbn\
                      \ attribute could be \"978-1-250-23-4567\"."
                    publicationYear: "The unique example value for the publicationYear\
                      \ attribute for Book with id 2 is 2018."
                  - id: 3
                    title: "\"The Great Gatsby\""
                    isbn: "The unique example value for the isbn attribute of a Book\
                      \ with id 3 could be \"978-1-56619-909-4\"."
                    publicationYear: "The unique publicationYear value for Book with\
                      \ id 3 is 2007."
                  - id: 4
                    title: "\"The Art of War\""
                    isbn: "For Book with id 4, a unique ISBN value could be \"978-1-4082-9997-3\"\
                      ."
                    publicationYear: "For Book with id 4, the publicationYear could\
                      \ be 2005."
                  - id: 5
                    title: "\"The Adventure of the Mysterious Island\""
                    isbn: "B6789451234"
                    publicationYear: "For Book with id 5, the publicationYear could\
                      \ be 2007."
                  - id: 6
                    title: "\"The Secret Life of Bees\""
                    isbn: "\"978-1-56619-909-4\""
                    publicationYear: "For Book with id 6, the unique publicationYear\
                      \ attribute value could be 2004."
                  - id: 7
                    title: "The unique title for Book with id 7 is \"The Midnight\
                      \ Library\"."
                    isbn: "\"978-0-306-40615-7\""
                    publicationYear: "For the Book with id 7, the unique publicationYear\
                      \ value could be 2005."
  /author:
    get:
      tags:
      - "Author"
      summary: "Get all instances of Author"
      description: "Fetches all instances of Author"
      responses:
        "200":
          description: "Successful retrieval"
          content:
            application/xml:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Author"
                xml:
                  wrapped: true
                  name: "author"
                  namespace: "http://example.com/schema"
              examples:
                exampleArray:
                  value:
                  - id: 1
                    name: "Author 1 - \"Eleanor Smith\""
                    birthYear: "If the Author with id 1 has a unique birth year value,\
                      \ an example could be:\n\n```json\n{\n  \"id\": 1,"
                  - id: 2
                    name: "For the Author with id 2, a unique name value could be\
                      \ \"Emily Smith\"."
                    birthYear: "For Author with id 2, a unique example value for the\
                      \ attribute birthYear could be 1984."
                  - id: 3
                    name: "Unique example value for name attribute of Author with\
                      \ id 3: \"Emily Thompson\""
                    birthYear: "Since I do not have access to external databases,\
                      \ I am unable to provide the exact birth year for an author\
                      \ with id 3. However, I"
                  - id: 4
                    name: "The unique example value for the name attribute of the\
                      \ Author with id 4 could be \"Jane Johnson\"."
                    birthYear: "For Author with id 4, the birthYear could be 1978."
                  - id: 5
                    name: "The unique example value for the name attribute of Author\
                      \ with id 5 can be \"Jane Smith\"."
                    birthYear: "Considering the uniqueness constraint and the id being\
                      \ 5, a unique value for the birthYear attribute for the Author\
                      \ class with id 5 could be:"
                  - id: 6
                    name: "Gina Smith"
                    birthYear: "If the id of the Author class is 6, a unique example\
                      \ value for the int attribute birthYear could be 1989."
                  - id: 7
                    name: "Author 7 Name: \"Emma Smith\""
                    birthYear: "For Author with id 7, a unique birthYear value could\
                      \ be 1985."
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Author"
                type: "array"
              examples:
                exampleArray:
                  value:
                  - id: 1
                    name: "Author 1 - \"Eleanor Smith\""
                    birthYear: "If the Author with id 1 has a unique birth year value,\
                      \ an example could be:\n\n```json\n{\n  \"id\": 1,"
                  - id: 2
                    name: "For the Author with id 2, a unique name value could be\
                      \ \"Emily Smith\"."
                    birthYear: "For Author with id 2, a unique example value for the\
                      \ attribute birthYear could be 1984."
                  - id: 3
                    name: "Unique example value for name attribute of Author with\
                      \ id 3: \"Emily Thompson\""
                    birthYear: "Since I do not have access to external databases,\
                      \ I am unable to provide the exact birth year for an author\
                      \ with id 3. However, I"
                  - id: 4
                    name: "The unique example value for the name attribute of the\
                      \ Author with id 4 could be \"Jane Johnson\"."
                    birthYear: "For Author with id 4, the birthYear could be 1978."
                  - id: 5
                    name: "The unique example value for the name attribute of Author\
                      \ with id 5 can be \"Jane Smith\"."
                    birthYear: "Considering the uniqueness constraint and the id being\
                      \ 5, a unique value for the birthYear attribute for the Author\
                      \ class with id 5 could be:"
                  - id: 6
                    name: "Gina Smith"
                    birthYear: "If the id of the Author class is 6, a unique example\
                      \ value for the int attribute birthYear could be 1989."
                  - id: 7
                    name: "Author 7 Name: \"Emma Smith\""
                    birthYear: "For Author with id 7, a unique birthYear value could\
                      \ be 1985."
  /library:
    get:
      tags:
      - "Library"
      summary: "Get all instances of Library"
      description: "Fetches all instances of Library"
      responses:
        "200":
          description: "Successful retrieval"
          content:
            application/xml:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Library"
                xml:
                  wrapped: true
                  name: "library"
                  namespace: "http://example.com/schema"
              examples:
                exampleArray:
                  value:
                  - id: 1
                    libraryName: "Library with id 1 has the unique libraryName value\
                      \ \"Sunset Valley Community Library\"."
                  - id: 2
                    libraryName: "The unique example value for the libraryName attribute\
                      \ of Library with id 2 could be \"Knowledge Haven Library\"."
                  - id: 3
                    libraryName: "libraryName: \"Springfield Central Library\""
                  - id: 4
                    libraryName: "libraryName: \"Summerfield Library\""
                  - id: 5
                    libraryName: "libraryName: \"Brighton Public Library\""
                  - id: 6
                    libraryName: "libraryName: \"Great Minds Public Library\""
                  - id: 7
                    libraryName: "Library 7 - \"Bookworm Haven\""
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Library"
                type: "array"
              examples:
                exampleArray:
                  value:
                  - id: 1
                    libraryName: "Library with id 1 has the unique libraryName value\
                      \ \"Sunset Valley Community Library\"."
                  - id: 2
                    libraryName: "The unique example value for the libraryName attribute\
                      \ of Library with id 2 could be \"Knowledge Haven Library\"."
                  - id: 3
                    libraryName: "libraryName: \"Springfield Central Library\""
                  - id: 4
                    libraryName: "libraryName: \"Summerfield Library\""
                  - id: 5
                    libraryName: "libraryName: \"Brighton Public Library\""
                  - id: 6
                    libraryName: "libraryName: \"Great Minds Public Library\""
                  - id: 7
                    libraryName: "Library 7 - \"Bookworm Haven\""
components:
  schemas:
    Plant:
      example:
        id: 1
        plantType: "\"Evergreen Shrub\""
      xml:
        wrapped: true
        name: "plant"
        namespace: "http://example.com/schema"
      type: "object"
      properties:
        plantType:
          type: "string"
      examples:
        exampleArray:
        - id: 1
          plantType: "\"Evergreen Shrub\""
        - id: 2
          plantType: "For the Plant with id 2, the unique example value for the plantType\
            \ attribute could be \"Cactus\"."
        - id: 3
          plantType: "For Plant with id 3, the unique example value for the plantType\
            \ attribute could be \"Succulent\"."
        - id: 4
          plantType: "\"Orchid\""
        - id: 5
          plantType: "For plant with id 5, the unique example value for the plantType\
            \ attribute could be \"Bromeliad\"."
        - id: 6
          plantType: "For Plant with id 6, the unique example value for the plantType\
            \ attribute could be \"Climbing Rose\"."
        - id: 7
          plantType: "Ferns and Mosses"
    Book:
      example:
        id: 1
        title: "\"The Enchanted Forest\""
        isbn: "For Book with id 1, a unique example value for the isbn attribute could\
          \ be \"978-1-250-75241-0\"."
        publicationYear: "A unique example value for publicationYear for a Book with\
          \ id 1 could be 2003."
      xml:
        wrapped: true
        name: "book"
        namespace: "http://example.com/schema"
      type: "object"
      properties:
        title:
          type: "string"
        isbn:
          type: "string"
        publicationYear:
          type: "integer"
          format: "int32"
      examples:
        exampleArray:
        - id: 1
          title: "\"The Enchanted Forest\""
          isbn: "For Book with id 1, a unique example value for the isbn attribute\
            \ could be \"978-1-250-75241-0\"."
          publicationYear: "A unique example value for publicationYear for a Book\
            \ with id 1 could be 2003."
        - id: 2
          title: "The unique example value for the String attribute title of a Book\
            \ with id 2 could be \"The Enigma of Probability\"."
          isbn: "For Book with id 2, a unique example value for the isbn attribute\
            \ could be \"978-1-250-23-4567\"."
          publicationYear: "The unique example value for the publicationYear attribute\
            \ for Book with id 2 is 2018."
        - id: 3
          title: "\"The Great Gatsby\""
          isbn: "The unique example value for the isbn attribute of a Book with id\
            \ 3 could be \"978-1-56619-909-4\"."
          publicationYear: "The unique publicationYear value for Book with id 3 is\
            \ 2007."
        - id: 4
          title: "\"The Art of War\""
          isbn: "For Book with id 4, a unique ISBN value could be \"978-1-4082-9997-3\"\
            ."
          publicationYear: "For Book with id 4, the publicationYear could be 2005."
        - id: 5
          title: "\"The Adventure of the Mysterious Island\""
          isbn: "B6789451234"
          publicationYear: "For Book with id 5, the publicationYear could be 2007."
        - id: 6
          title: "\"The Secret Life of Bees\""
          isbn: "\"978-1-56619-909-4\""
          publicationYear: "For Book with id 6, the unique publicationYear attribute\
            \ value could be 2004."
        - id: 7
          title: "The unique title for Book with id 7 is \"The Midnight Library\"."
          isbn: "\"978-0-306-40615-7\""
          publicationYear: "For the Book with id 7, the unique publicationYear value\
            \ could be 2005."
    Author:
      example:
        id: 1
        name: "Author 1 - \"Eleanor Smith\""
        birthYear: "If the Author with id 1 has a unique birth year value, an example\
          \ could be:\n\n```json\n{\n  \"id\": 1,"
      xml:
        wrapped: true
        name: "author"
        namespace: "http://example.com/schema"
      type: "object"
      properties:
        name:
          type: "string"
        birthYear:
          type: "integer"
          format: "int32"
      examples:
        exampleArray:
        - id: 1
          name: "Author 1 - \"Eleanor Smith\""
          birthYear: "If the Author with id 1 has a unique birth year value, an example\
            \ could be:\n\n```json\n{\n  \"id\": 1,"
        - id: 2
          name: "For the Author with id 2, a unique name value could be \"Emily Smith\"\
            ."
          birthYear: "For Author with id 2, a unique example value for the attribute\
            \ birthYear could be 1984."
        - id: 3
          name: "Unique example value for name attribute of Author with id 3: \"Emily\
            \ Thompson\""
          birthYear: "Since I do not have access to external databases, I am unable\
            \ to provide the exact birth year for an author with id 3. However, I"
        - id: 4
          name: "The unique example value for the name attribute of the Author with\
            \ id 4 could be \"Jane Johnson\"."
          birthYear: "For Author with id 4, the birthYear could be 1978."
        - id: 5
          name: "The unique example value for the name attribute of Author with id\
            \ 5 can be \"Jane Smith\"."
          birthYear: "Considering the uniqueness constraint and the id being 5, a\
            \ unique value for the birthYear attribute for the Author class with id\
            \ 5 could be:"
        - id: 6
          name: "Gina Smith"
          birthYear: "If the id of the Author class is 6, a unique example value for\
            \ the int attribute birthYear could be 1989."
        - id: 7
          name: "Author 7 Name: \"Emma Smith\""
          birthYear: "For Author with id 7, a unique birthYear value could be 1985."
    Library:
      example:
        id: 1
        libraryName: "Library with id 1 has the unique libraryName value \"Sunset\
          \ Valley Community Library\"."
      xml:
        wrapped: true
        name: "library"
        namespace: "http://example.com/schema"
      type: "object"
      properties:
        libraryName:
          type: "string"
      examples:
        exampleArray:
        - id: 1
          libraryName: "Library with id 1 has the unique libraryName value \"Sunset\
            \ Valley Community Library\"."
        - id: 2
          libraryName: "The unique example value for the libraryName attribute of\
            \ Library with id 2 could be \"Knowledge Haven Library\"."
        - id: 3
          libraryName: "libraryName: \"Springfield Central Library\""
        - id: 4
          libraryName: "libraryName: \"Summerfield Library\""
        - id: 5
          libraryName: "libraryName: \"Brighton Public Library\""
        - id: 6
          libraryName: "libraryName: \"Great Minds Public Library\""
        - id: 7
          libraryName: "Library 7 - \"Bookworm Haven\""
