---
openapi: "3.0.0"
info:
  title: "Generated API"
  version: "1.0.0"
  description: "API dynamically generated from UML."
servers:
- url: "http://localhost:4010"
paths:
  /building:
    get:
      tags:
      - "Building"
      summary: "Get all instances of Building"
      description: "Fetches all instances of Building"
      responses:
        "200":
          content:
            application/xml:
              schema:
                xml:
                  name: "building"
                  wrapped: true
                  namespace: "http://example.com/schema"
                items:
                  $ref: "#/components/schemas/Building"
                type: "array"
              examples:
                exampleArray:
                  value:
                  - id: 1
                    buildingType: "Skyscraper"
                  - id: 2
                    buildingType: "\"commercial\""
                  - id: 3
                    buildingType: "Hut"
                  - id: 4
                    buildingType: "buildingType: \"Skyscraper\""
                  - id: 5
                    buildingType: "Skyscraper"
                  - id: 6
                    buildingType: "Commercial Office Building"
                  - id: 7
                    buildingType: "Building with id 7 has a buildingType attribute\
                      \ value of \"Corporate Office Building\"."
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Building"
                type: "array"
              examples:
                exampleArray:
                  value:
                  - id: 1
                    buildingType: "Skyscraper"
                  - id: 2
                    buildingType: "\"commercial\""
                  - id: 3
                    buildingType: "Hut"
                  - id: 4
                    buildingType: "buildingType: \"Skyscraper\""
                  - id: 5
                    buildingType: "Skyscraper"
                  - id: 6
                    buildingType: "Commercial Office Building"
                  - id: 7
                    buildingType: "Building with id 7 has a buildingType attribute\
                      \ value of \"Corporate Office Building\"."
          description: "Successful retrieval"
    post:
      tags:
      - "Building"
      summary: "POST operation for Building"
      description: "Performs POST operation for Building"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Building"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Building"
          application/xml:
            schema:
              $ref: "#/components/schemas/Building"
        description: "Payload for POST operation"
        required: true
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Building"
            application/json:
              schema:
                $ref: "#/components/schemas/Building"
          description: "Successful operation"
  /building/{id}:
    delete:
      tags:
      - "Building"
      summary: "DELETE operation for Building"
      description: "Performs DELETE operation for Building"
      parameters:
      - in: "path"
        name: "id"
        schema:
          type: "string"
        required: true
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Building"
            application/json:
              schema:
                $ref: "#/components/schemas/Building"
          description: "Successful operation"
    get:
      tags:
      - "Building"
      summary: "GET operation for Building"
      description: "Performs GET operation for Building"
      parameters:
      - in: "path"
        name: "id"
        schema:
          type: "string"
        required: true
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Building"
              examples:
                "1":
                  value:
                    id: 1
                    buildingType: "buildingType: \"Skyscraper\""
                "2":
                  value:
                    id: 2
                    buildingType: "\"commercial\""
                "3":
                  value:
                    id: 3
                    buildingType: "For Building with id 3, the unique buildingType\
                      \ could be \"Skyscraper\"."
                "4":
                  value:
                    id: 4
                    buildingType: "buildingType: \"Skyscraper\""
                "5":
                  value:
                    id: 5
                    buildingType: "Skyscraper"
                "6":
                  value:
                    id: 6
                    buildingType: "Commercial Office Building"
                "7":
                  value:
                    id: 7
                    buildingType: "Building with id 7 has a buildingType attribute\
                      \ value of \"Corporate Office Building\"."
            application/json:
              schema:
                $ref: "#/components/schemas/Building"
              examples:
                "1":
                  value:
                    id: 1
                    buildingType: "buildingType: \"Skyscraper\""
                "2":
                  value:
                    id: 2
                    buildingType: "\"commercial\""
                "3":
                  value:
                    id: 3
                    buildingType: "For Building with id 3, the unique buildingType\
                      \ could be \"Skyscraper\"."
                "4":
                  value:
                    id: 4
                    buildingType: "buildingType: \"Skyscraper\""
                "5":
                  value:
                    id: 5
                    buildingType: "Skyscraper"
                "6":
                  value:
                    id: 6
                    buildingType: "Commercial Office Building"
                "7":
                  value:
                    id: 7
                    buildingType: "Building with id 7 has a buildingType attribute\
                      \ value of \"Corporate Office Building\"."
          description: "Successful operation"
    put:
      tags:
      - "Building"
      summary: "PUT operation for Building"
      description: "Performs PUT operation for Building"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Building"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Building"
          application/xml:
            schema:
              $ref: "#/components/schemas/Building"
        description: "Payload for PUT operation"
        required: true
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Building"
            application/json:
              schema:
                $ref: "#/components/schemas/Building"
          description: "Successful operation"
  /library:
    get:
      tags:
      - "Library"
      summary: "Get all instances of Library"
      description: "Fetches all instances of Library"
      responses:
        "200":
          content:
            application/xml:
              schema:
                xml:
                  name: "library"
                  wrapped: true
                  namespace: "http://example.com/schema"
                items:
                  $ref: "#/components/schemas/Library"
                type: "array"
              examples:
                exampleArray:
                  value:
                  - id: 1
                    libraryName: "Renamed Library"
                  - id: 2
                    libraryName: "libraryName: \"Sunrise Library\""
                  - id: 3
                    libraryName: "Library 3 - \"Book Haven\""
                  - id: 4
                    libraryName: "libraryName: \"Wonderland_Public_Library_4\""
                  - id: 5
                    libraryName: "The unique example value for Library with id 5 attribute\
                      \ libraryName could be \"Dreamland Public Library\"."
                  - id: 6
                    libraryName: "The unique example value for the libraryName attribute\
                      \ of Library with id 6 could be \"Golden Gate Public Library\"\
                      ."
                  - id: 7
                    libraryName: "libraryName: \"Sunshine Valley Public Library\""
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Library"
                type: "array"
              examples:
                exampleArray:
                  value:
                  - id: 1
                    libraryName: "Renamed Library"
                  - id: 2
                    libraryName: "libraryName: \"Sunrise Library\""
                  - id: 3
                    libraryName: "Library 3 - \"Book Haven\""
                  - id: 4
                    libraryName: "libraryName: \"Wonderland_Public_Library_4\""
                  - id: 5
                    libraryName: "The unique example value for Library with id 5 attribute\
                      \ libraryName could be \"Dreamland Public Library\"."
                  - id: 6
                    libraryName: "The unique example value for the libraryName attribute\
                      \ of Library with id 6 could be \"Golden Gate Public Library\"\
                      ."
                  - id: 7
                    libraryName: "libraryName: \"Sunshine Valley Public Library\""
          description: "Successful retrieval"
    post:
      tags:
      - "Library"
      summary: "POST operation for Library"
      description: "Performs POST operation for Library"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Library"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Library"
          application/xml:
            schema:
              $ref: "#/components/schemas/Library"
        description: "Payload for POST operation"
        required: true
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Library"
            application/json:
              schema:
                $ref: "#/components/schemas/Library"
          description: "Successful operation"
  /library/{id}:
    delete:
      tags:
      - "Library"
      summary: "DELETE operation for Library"
      description: "Performs DELETE operation for Library"
      parameters:
      - in: "path"
        name: "id"
        schema:
          type: "string"
        required: true
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Library"
            application/json:
              schema:
                $ref: "#/components/schemas/Library"
          description: "Successful operation"
    get:
      tags:
      - "Library"
      summary: "GET operation for Library"
      description: "Performs GET operation for Library"
      parameters:
      - in: "path"
        name: "id"
        schema:
          type: "string"
        required: true
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Library"
              examples:
                "1":
                  value:
                    id: 1
                    libraryName: "CoolReader'sArchiveLib"
                "2":
                  value:
                    id: 2
                    libraryName: "libraryName: \"Sunrise Library\""
                "3":
                  value:
                    id: 3
                    libraryName: "Library 3 - \"Book Haven\""
                "4":
                  value:
                    id: 4
                    libraryName: "libraryName: \"Wonderland_Public_Library_4\""
                "5":
                  value:
                    id: 5
                    libraryName: "The unique example value for Library with id 5 attribute\
                      \ libraryName could be \"Dreamland Public Library\"."
                "6":
                  value:
                    id: 6
                    libraryName: "The unique example value for the libraryName attribute\
                      \ of Library with id 6 could be \"Golden Gate Public Library\"\
                      ."
                "7":
                  value:
                    id: 7
                    libraryName: "libraryName: \"Sunshine Valley Public Library\""
            application/json:
              schema:
                $ref: "#/components/schemas/Library"
              examples:
                "1":
                  value:
                    id: 1
                    libraryName: "CoolReader'sArchiveLib"
                "2":
                  value:
                    id: 2
                    libraryName: "libraryName: \"Sunrise Library\""
                "3":
                  value:
                    id: 3
                    libraryName: "Library 3 - \"Book Haven\""
                "4":
                  value:
                    id: 4
                    libraryName: "libraryName: \"Wonderland_Public_Library_4\""
                "5":
                  value:
                    id: 5
                    libraryName: "The unique example value for Library with id 5 attribute\
                      \ libraryName could be \"Dreamland Public Library\"."
                "6":
                  value:
                    id: 6
                    libraryName: "The unique example value for the libraryName attribute\
                      \ of Library with id 6 could be \"Golden Gate Public Library\"\
                      ."
                "7":
                  value:
                    id: 7
                    libraryName: "libraryName: \"Sunshine Valley Public Library\""
          description: "Successful operation"
    put:
      tags:
      - "Library"
      summary: "PUT operation for Library"
      description: "Performs PUT operation for Library"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Library"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Library"
          application/xml:
            schema:
              $ref: "#/components/schemas/Library"
        description: "Payload for PUT operation"
        required: true
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Library"
            application/json:
              schema:
                $ref: "#/components/schemas/Library"
          description: "Successful operation"
components:
  schemas:
    Building:
      examples:
        exampleArray:
        - id: 1
          buildingType: "Skyscraper"
        - id: 2
          buildingType: "\"commercial\""
        - id: 3
          buildingType: "Hut"
        - id: 4
          buildingType: "buildingType: \"Skyscraper\""
        - id: 5
          buildingType: "Skyscraper"
        - id: 6
          buildingType: "Commercial Office Building"
        - id: 7
          buildingType: "Building with id 7 has a buildingType attribute value of\
            \ \"Corporate Office Building\"."
      properties:
        buildingType:
          type: "string"
      type: "object"
      xml:
        name: "building"
        wrapped: true
        namespace: "http://example.com/schema"
      example:
        id: 1
        buildingType: "buildingType: \"Skyscraper\""
    Library:
      examples:
        exampleArray:
        - id: 1
          libraryName: "Renamed Library"
        - id: 2
          libraryName: "libraryName: \"Sunrise Library\""
        - id: 3
          libraryName: "Library 3 - \"Book Haven\""
        - id: 4
          libraryName: "libraryName: \"Wonderland_Public_Library_4\""
        - id: 5
          libraryName: "The unique example value for Library with id 5 attribute libraryName\
            \ could be \"Dreamland Public Library\"."
        - id: 6
          libraryName: "The unique example value for the libraryName attribute of\
            \ Library with id 6 could be \"Golden Gate Public Library\"."
        - id: 7
          libraryName: "libraryName: \"Sunshine Valley Public Library\""
      properties:
        libraryName:
          type: "string"
      type: "object"
      xml:
        name: "library"
        wrapped: true
        namespace: "http://example.com/schema"
      example:
        id: 1
        libraryName: "CoolReader'sArchiveLib"
